export default {
  TODO: {
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
  },
  TICKER: {
    INCREMENT_TICKER: "INCREMENT_TICKER",
    DECREMENT_TICKER: "DECREMENT_TICKER"
  }
}
